### ISSUE TITLE
Can only pull in daily data

### ISSUE THREAD

**Issue by 2firstnames** [TaylorFacen/nomics-python#18]
Hi there thanks for all of your hard work on this Python wrapper.

When I pull data using get_candles function, I can only retrieve data on the daily interval. All other intervals return daily data for me.

nomics.get_candles(interval = "5m", currency = ticker, start = date_start, end = date_today)

**Comment by 2firstnames** [comment]
If you can point me to the related files and functions I can update the code. Thanks!

**Comment by TaylorFacen** [comment]
Hey @2firstnames , thanks for mentioning this. I just updated the wrapper so now you should be able to more than just daily data. Can you try and let me know?

**Comment by TaylorFacen** [comment]
Closing due to no response.
