### ISSUE TITLE
readme suggestion

### ISSUE THREAD

**Issue by maxrottersman** [TaylorFacen/nomics-python#31]
Hi, you might put **pip install nomics-python** in your github project readme.  I couldn't figure it out until I read your post in the Nomics forum. 

Also you might put in simple demo code with a print statement at the end.  I  tried something like

`import nomics
nomics = nomics.Nomics("mykey")
res = nomics.Currencies.get_currencies(
    ids = ["BTC", "ETH"],
    interval = ["1d", "ytd"],
    convert = "EUR"
)

print(res)`

But that didn't work.  Got

`ERROR: Directory 'c:\\Files2020_Dev\\ByProject\\APIs_Various' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`

THANKS!  I look forward to using it!

**Comment by TaylorFacen** [comment]
Thanks @maxrottersman ! I've updated the readme to include the installation instructions. Also, I just refactored the entire wrapper to get rid of some errors. Can you update to the newest version and try again?

**Comment by maxrottersman** [comment]
Thanks!  I'm in the middle of other headaches, but hope to get back to this stuff soon!  Will let you know!

**Comment by TaylorFacen** [comment]
Closing due to no response. If you're still seeing the same issue, let me know!
