### ISSUE TITLE
Issue filtering get_currencies with multiple ids

### ISSUE THREAD

**Issue by MBearr1221** [TaylorFacen/nomics-python#32]
The currencies call:
nomics.Currencies.get_currencies(ids=['BTC', 'ETC'], interval='1d')
has had no issues since I started using it a few weeks back, but a couple days ago, it stopped filtering for the ids I put in as a list and now it only returns the first element of the ids list.

**Comment by TaylorFacen** [comment]
Hi @MBearr1221 , this is now fixed. Please update to the newest package version and let me know if you're still running into any errors.
